CREATE USER 'zhanjiahao'@'%' IDENTIFIED WITH mysql_native_password;GRANT USAGE ON *.* TO 'zhanjiahao'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;SET PASSWORD FOR 'zhanjiahao'@'%' = '***';




GRANT ALL PRIVILEGES ON `db\_super\_desk`.* TO 'zhanjiahao'@'%' WITH GRANT OPTION;