





# 已更新到 福利内购
# 已更新到 企业采购






SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for ims_superdesk_shop_express
-- ----------------------------
DROP TABLE IF EXISTS `ims_superdesk_shop_express`;
CREATE TABLE `ims_superdesk_shop_express` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT '',
  `express` varchar(50) DEFAULT '',
  `status` tinyint(1) DEFAULT '1',
  `displayorder` tinyint(3) unsigned DEFAULT '0',
  `code` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ims_superdesk_shop_express
-- ----------------------------
INSERT INTO `ims_superdesk_shop_express` VALUES ('1', '顺丰', 'shunfeng', '1', '0', 'SF');
INSERT INTO `ims_superdesk_shop_express` VALUES ('2', '申通', 'shentong', '1', '0', 'STO');
INSERT INTO `ims_superdesk_shop_express` VALUES ('3', '韵达快运', 'yunda', '1', '0', 'YD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('4', '天天快递', 'tiantian', '1', '0', 'HHTT');
INSERT INTO `ims_superdesk_shop_express` VALUES ('5', '圆通速递', 'yuantong', '1', '0', 'YTO');
INSERT INTO `ims_superdesk_shop_express` VALUES ('6', '中通速递', 'zhongtong', '1', '0', 'ZTO');
INSERT INTO `ims_superdesk_shop_express` VALUES ('7', 'ems快递', 'ems', '1', '0', 'EMS');
INSERT INTO `ims_superdesk_shop_express` VALUES ('8', '百世汇通', 'huitongkuaidi', '1', '0', 'HTKY');
INSERT INTO `ims_superdesk_shop_express` VALUES ('9', '全峰快递', 'quanfengkuaidi', '0', '0', 'JH_009');
INSERT INTO `ims_superdesk_shop_express` VALUES ('10', '宅急送', 'zhaijisong', '1', '0', 'ZJS');
INSERT INTO `ims_superdesk_shop_express` VALUES ('11', 'aae全球专递', 'aae', '1', '0', 'AAE');
INSERT INTO `ims_superdesk_shop_express` VALUES ('12', '安捷快递', 'anjie', '1', '0', 'AJ');
INSERT INTO `ims_superdesk_shop_express` VALUES ('13', '安信达快递', 'anxindakuaixi', '0', '0', 'JH_131');
INSERT INTO `ims_superdesk_shop_express` VALUES ('14', '彪记快递', 'biaojikuaidi', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('15', 'bht', 'bht', '1', '0', 'BHT');
INSERT INTO `ims_superdesk_shop_express` VALUES ('16', '百福东方国际物流', 'baifudongfang', '1', '0', 'BFDF');
INSERT INTO `ims_superdesk_shop_express` VALUES ('17', '中国东方（COE）', 'coe', '1', '0', 'COE');
INSERT INTO `ims_superdesk_shop_express` VALUES ('18', '长宇物流', 'changyuwuliu', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('19', '大田物流', 'datianwuliu', '1', '0', 'DTWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('20', '德邦物流', 'debangwuliu', '1', '0', 'DBL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('21', 'dhl', 'dhl', '1', '0', 'DHL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('22', 'dpex', 'dpex', '1', '0', 'DPEX');
INSERT INTO `ims_superdesk_shop_express` VALUES ('23', 'd速快递', 'dsukuaidi', '1', '0', 'DSWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('24', '递四方', 'disifang', '0', '0', 'JHI_080');
INSERT INTO `ims_superdesk_shop_express` VALUES ('25', 'fedex（国外）', 'fedex', '1', '0', 'FEDEX_GJ');
INSERT INTO `ims_superdesk_shop_express` VALUES ('26', '飞康达物流', 'feikangda', '1', '0', 'FKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('27', '凤凰快递', 'fenghuangkuaidi', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('28', '飞快达', 'feikuaida', '0', '0', 'JH_151');
INSERT INTO `ims_superdesk_shop_express` VALUES ('29', '国通快递', 'guotongkuaidi', '1', '0', 'GTO');
INSERT INTO `ims_superdesk_shop_express` VALUES ('30', '港中能达物流', 'ganzhongnengda', '1', '0', 'NEDA');
INSERT INTO `ims_superdesk_shop_express` VALUES ('31', '广东邮政物流', 'guangdongyouzhengwuliu', '1', '0', 'GDEMS');
INSERT INTO `ims_superdesk_shop_express` VALUES ('32', '共速达', 'gongsuda', '1', '0', 'GSD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('33', '恒路物流', 'hengluwuliu', '1', '0', 'HLWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('34', '华夏龙物流', 'huaxialongwuliu', '1', '0', 'HXLWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('35', '海红', 'haihongwangsong', '0', '0', 'JH_132');
INSERT INTO `ims_superdesk_shop_express` VALUES ('36', '海外环球', 'haiwaihuanqiu', '1', '0', 'JHI_013');
INSERT INTO `ims_superdesk_shop_express` VALUES ('37', '佳怡物流', 'jiayiwuliu', '1', '0', 'JYWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('38', '京广速递', 'jinguangsudikuaijian', '1', '0', 'JGSD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('39', '急先达', 'jixianda', '1', '0', 'JXD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('40', '佳吉物流', 'jiajiwuliu', '0', '0', 'JH_030');
INSERT INTO `ims_superdesk_shop_express` VALUES ('41', '加运美物流', 'jymwl', '1', '0', 'JYM');
INSERT INTO `ims_superdesk_shop_express` VALUES ('42', '金大物流', 'jindawuliu', '0', '0', 'JH_079');
INSERT INTO `ims_superdesk_shop_express` VALUES ('43', '嘉里大通', 'jialidatong', '0', '0', 'JH_060');
INSERT INTO `ims_superdesk_shop_express` VALUES ('44', '晋越快递', 'jykd', '1', '0', 'JYKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('45', '快捷速递', 'kuaijiesudi', '1', '0', 'JH_008');
INSERT INTO `ims_superdesk_shop_express` VALUES ('46', '联邦快递（国内）', 'lianb', '1', '0', 'FEDEX');
INSERT INTO `ims_superdesk_shop_express` VALUES ('47', '联昊通物流', 'lianhaowuliu', '1', '0', 'LHT');
INSERT INTO `ims_superdesk_shop_express` VALUES ('48', '龙邦物流', 'longbanwuliu', '1', '0', 'LB');
INSERT INTO `ims_superdesk_shop_express` VALUES ('49', '立即送', 'lijisong', '1', '0', 'LJSKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('50', '乐捷递', 'lejiedi', '0', '0', 'JH_043');
INSERT INTO `ims_superdesk_shop_express` VALUES ('51', '民航快递', 'minghangkuaidi', '1', '0', 'MHKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('52', '美国快递', 'meiguokuaidi', '0', '0', 'MDM');
INSERT INTO `ims_superdesk_shop_express` VALUES ('53', '门对门', 'menduimen', '1', '0', 'MDM');
INSERT INTO `ims_superdesk_shop_express` VALUES ('54', 'OCS', 'ocs', '1', '0', 'OCS');
INSERT INTO `ims_superdesk_shop_express` VALUES ('55', '配思货运', 'peisihuoyunkuaidi', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('56', '全晨快递', 'quanchenkuaidi', '1', '0', 'QCKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('57', '全际通物流', 'quanjitong', '0', '0', 'JH_127');
INSERT INTO `ims_superdesk_shop_express` VALUES ('58', '全日通快递', 'quanritongkuaidi', '1', '0', 'QRT');
INSERT INTO `ims_superdesk_shop_express` VALUES ('59', '全一快递', 'quanyikuaidi', '1', '0', 'UAPEX');
INSERT INTO `ims_superdesk_shop_express` VALUES ('60', '如风达', 'rufengda', '1', '0', 'RFD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('61', '三态速递', 'santaisudi', '0', '0', 'JH_065');
INSERT INTO `ims_superdesk_shop_express` VALUES ('62', '盛辉物流', 'shenghuiwuliu', '0', '0', 'JH_066');
INSERT INTO `ims_superdesk_shop_express` VALUES ('63', '速尔物流', 'sue', '1', '0', 'SURE');
INSERT INTO `ims_superdesk_shop_express` VALUES ('64', '盛丰物流', 'shengfeng', '1', '0', 'SFWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('65', '赛澳递', 'saiaodi', '1', '0', 'SAD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('66', '天地华宇', 'tiandihuayu', '1', '0', 'HOAU');
INSERT INTO `ims_superdesk_shop_express` VALUES ('67', 'tnt', 'tnt', '1', '0', 'TNT');
INSERT INTO `ims_superdesk_shop_express` VALUES ('68', 'ups', 'ups', '1', '0', 'UPS');
INSERT INTO `ims_superdesk_shop_express` VALUES ('69', '万家物流', 'wanjiawuliu', '1', '0', 'WJWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('70', '文捷航空速递', 'wenjiesudi', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('71', '伍圆', 'wuyuan', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('72', '万象物流', 'wxwl', '0', '0', 'JH_115');
INSERT INTO `ims_superdesk_shop_express` VALUES ('73', '新邦物流', 'xinbangwuliu', '0', '0', 'JH_022');
INSERT INTO `ims_superdesk_shop_express` VALUES ('74', '信丰物流', 'xinfengwuliu', '1', '0', 'XFEX');
INSERT INTO `ims_superdesk_shop_express` VALUES ('75', '亚风速递', 'yafengsudi', '1', '0', 'YFSD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('76', '一邦速递', 'yibangwuliu', '0', '0', 'JH_064');
INSERT INTO `ims_superdesk_shop_express` VALUES ('77', '优速物流', 'youshuwuliu', '1', '0', 'UC');
INSERT INTO `ims_superdesk_shop_express` VALUES ('78', '邮政快递包裹', 'youzhengguonei', '1', '0', 'YZPY');
INSERT INTO `ims_superdesk_shop_express` VALUES ('79', '邮政国际包裹挂号信', 'youzhengguoji', '0', '0', '');
INSERT INTO `ims_superdesk_shop_express` VALUES ('80', '远成物流', 'yuanchengwuliu', '1', '0', 'YCWL');
INSERT INTO `ims_superdesk_shop_express` VALUES ('81', '源伟丰快递', 'yuanweifeng', '0', '0', 'JH_141');
INSERT INTO `ims_superdesk_shop_express` VALUES ('82', '元智捷诚快递', 'yuanzhijiecheng', '0', '0', 'JH_126');
INSERT INTO `ims_superdesk_shop_express` VALUES ('83', '运通快递', 'yuntongkuaidi', '1', '0', 'YTKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('84', '越丰物流', 'yuefengwuliu', '1', '0', 'YFEX');
INSERT INTO `ims_superdesk_shop_express` VALUES ('85', '源安达', 'yad', '1', '0', 'YADEX');
INSERT INTO `ims_superdesk_shop_express` VALUES ('86', '银捷速递', 'yinjiesudi', '0', '0', 'JH_148');
INSERT INTO `ims_superdesk_shop_express` VALUES ('87', '中铁快运', 'zhongtiekuaiyun', '1', '0', 'ZTKY');
INSERT INTO `ims_superdesk_shop_express` VALUES ('88', '中邮物流', 'zhongyouwuliu', '1', '0', 'ZYKD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('89', '忠信达', 'zhongxinda', '0', '0', 'JH_086');
INSERT INTO `ims_superdesk_shop_express` VALUES ('90', '芝麻开门', 'zhimakaimen', '0', '0', 'JH_026');
INSERT INTO `ims_superdesk_shop_express` VALUES ('91', '安能物流', 'annengwuliu', '1', '0', 'ANE');
INSERT INTO `ims_superdesk_shop_express` VALUES ('92', '京东快递', 'jd', '1', '0', 'JD');
INSERT INTO `ims_superdesk_shop_express` VALUES ('93', '微特派', 'weitepai', '1', '0', 'WTP');
INSERT INTO `ims_superdesk_shop_express` VALUES ('94', '九曳供应链', 'jiuyescm', '1', '0', 'JIUYE');

-- ----------------------------
-- Table structure for ims_superdesk_shop_express_kdniao
-- ----------------------------
DROP TABLE IF EXISTS `ims_superdesk_shop_express_kdniao`;
CREATE TABLE `ims_superdesk_shop_express_kdniao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=421 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ims_superdesk_shop_express_kdniao
-- ----------------------------
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('1', '顺丰速运', 'SF');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('2', '百世快递', 'HTKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('3', '中通快递', 'ZTO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('4', '申通快递', 'STO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('5', '圆通速递', 'YTO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('6', '韵达速递', 'YD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('7', '邮政快递包裹', 'YZPY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('8', 'EMS', 'EMS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('9', '天天快递', 'HHTT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('10', '京东快递', 'JD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('11', '优速快递', 'UC');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('12', '德邦快递', 'DBL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('13', '宅急送', 'ZJS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('14', 'TNT快递', 'TNT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('15', 'UPS', 'UPS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('16', 'DHL', 'DHL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('17', 'FEDEX联邦(国内件）', 'FEDEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('18', 'FEDEX联邦(国际件）', 'FEDEX_GJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('19', '安捷快递', 'AJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('20', '阿里跨境电商物流', 'ALKJWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('21', '安讯物流', 'AXWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('22', '安邮美国', 'AYUS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('23', '亚马逊物流', 'AMAZON');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('24', '澳门邮政', 'AOMENYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('25', '安能物流', 'ANE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('26', '澳多多', 'ADD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('27', '澳邮专线', 'AYCA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('28', '安鲜达', 'AXD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('29', '安能快运', 'ANEKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('30', '八达通  ', 'BDT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('31', '百腾物流', 'BETWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('32', '北极星快运', 'BJXKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('33', '奔腾物流', 'BNTWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('34', '百福东方', 'BFDF');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('35', '贝海国际 ', 'BHGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('36', '八方安运', 'BFAY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('37', '百世快运', 'BTWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('38', '春风物流', 'CFWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('39', '诚通物流', 'CHTWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('40', '传喜物流', 'CXHY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('41', '程光   ', 'CG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('42', '城市100', 'CITY100');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('43', '城际快递', 'CJKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('44', 'CNPEX中邮快递', 'CNPEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('45', 'COE东方快递', 'COE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('46', '长沙创一', 'CSCY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('47', '成都善途速运', 'CDSTKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('48', '联合运通', 'CTG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('49', '疯狂快递', 'CRAZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('50', 'CBO钏博物流', 'CBO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('51', '承诺达', 'CND');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('52', 'D速物流', 'DSWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('53', '到了港', 'DLG ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('54', '大田物流', 'DTWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('55', '东骏快捷物流', 'DJKJWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('56', '德坤', 'DEKUN');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('57', '德邦快运', 'DBLKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('58', 'E特快', 'ETK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('59', 'EWE', 'EWE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('60', '快服务', 'KFW');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('61', '飞康达', 'FKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('62', '富腾达  ', 'FTD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('63', '凡宇货的', 'FYKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('64', '速派快递', 'FASTGO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('65', '丰通快运', 'FT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('66', '冠达   ', 'GD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('67', '国通快递', 'GTO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('68', '广东邮政', 'GDEMS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('69', '共速达', 'GSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('70', '广通       ', 'GTONG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('71', '迦递快递', 'GAI');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('72', '港快速递', 'GKSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('73', '高铁速递', 'GTSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('74', '汇丰物流', 'HFWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('75', '黑狗冷链', 'HGLL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('76', '恒路物流', 'HLWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('77', '天地华宇', 'HOAU');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('78', '鸿桥供应链', 'HOTSCM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('79', '海派通物流公司', 'HPTEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('80', '华强物流', 'hq568');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('81', '环球速运  ', 'HQSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('82', '华夏龙物流', 'HXLWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('83', '豪翔物流 ', 'HXWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('84', '合肥汇文', 'HFHW');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('85', '辉隆物流', 'HLONGWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('86', '华企快递', 'HQKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('87', '韩润物流', 'HRWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('88', '青岛恒通快递', 'HTKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('89', '货运皇物流', 'HYH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('90', '好来运快递', 'HYLSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('91', '皇家物流', 'HJWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('92', '捷安达  ', 'JAD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('93', '京广速递', 'JGSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('94', '九曳供应链', 'JIUYE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('95', '急先达', 'JXD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('96', '晋越快递', 'JYKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('97', '加运美', 'JYM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('98', '景光物流', 'JGWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('99', '佳怡物流', 'JYWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('100', '京东快运', 'JDKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('101', '跨越速运', 'KYSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('102', '跨越物流', 'KYWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('103', '快速递物流', 'KSDWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('104', '龙邦快递', 'LB');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('105', '立即送', 'LJSKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('106', '联昊通速递', 'LHT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('107', '民邦快递', 'MB');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('108', '民航快递', 'MHKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('109', '美快    ', 'MK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('110', '门对门快递', 'MDM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('111', '迈隆递运', 'MRDY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('112', '明亮物流', 'MLWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('113', '南方', 'NF');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('114', '能达速递', 'NEDA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('115', '平安达腾飞快递', 'PADTF');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('116', '泛捷快递', 'PANEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('117', '品骏快递', 'PJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('118', 'PCA Express', 'PCA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('119', '全晨快递', 'QCKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('120', '全日通快递', 'QRT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('121', '快客快递', 'QUICK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('122', '全信通', 'QXT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('123', '如风达', 'RFD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('124', '日日顺物流', 'RRS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('125', '瑞丰速递', 'RFEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('126', '赛澳递', 'SAD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('127', '苏宁物流', 'SNWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('128', '圣安物流', 'SAWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('129', '晟邦物流', 'SBWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('130', '上大物流', 'SDWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('131', '盛丰物流', 'SFWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('132', '速通物流', 'ST');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('133', '速腾快递', 'STWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('134', '速必达物流', 'SUBIDA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('135', '速递e站', 'SDEZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('136', '速呈宅配', 'SCZPDS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('137', '速尔快递', 'SURE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('138', '台湾邮政', 'TAIWANYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('139', '唐山申通', 'TSSTO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('140', '通用物流', 'TYWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('141', '全一快递', 'UAPEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('142', '优联吉运', 'ULUCKEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('143', 'UEQ Express', 'UEQ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('144', '万家康  ', 'WJK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('145', '万家物流', 'WJWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('146', '武汉同舟行', 'WHTZX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('147', '维普恩', 'WPE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('148', '微特派', 'WTP');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('149', '迅驰物流  ', 'XCWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('150', '信丰物流', 'XFEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('151', '希优特', 'XYT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('152', '新杰物流', 'XJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('153', '源安达快递', 'YADEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('154', '远成物流', 'YCWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('155', '远成快运', 'YCSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('156', '义达国际物流', 'YDH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('157', '易达通  ', 'YDT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('158', '越丰物流', 'YFEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('159', '原飞航物流', 'YFHEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('160', '亚风快递', 'YFSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('161', '运通快递', 'YTKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('162', '亿翔快递', 'YXKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('163', '运东西网', 'YUNDX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('164', '壹米滴答', 'YMDD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('165', '邮政国内标快', 'YZBK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('166', '一站通速运', 'YZTSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('167', '驭丰速运', 'YFSUYUN');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('168', '增益快递', 'ZENY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('169', '汇强快递', 'ZHQKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('170', '众通快递', 'ZTE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('171', '中铁快运', 'ZTKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('172', '中铁物流', 'ZTWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('173', '郑州速捷', 'SJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('174', '中通快运', 'ZTOKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('175', '中邮快递', 'ZYKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('176', '中粮我买网', 'WM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('177', '', '');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('178', 'AAE全球专递', 'AAE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('179', 'ACS雅仕快递', 'ACS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('180', 'ADP Express Tracking', 'ADP');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('181', '安圭拉邮政', 'ANGUILAYOU');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('182', 'APAC', 'APAC');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('183', 'Aramex', 'ARAMEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('184', '奥地利邮政', 'AT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('185', 'Australia Post Tracking', 'AUSTRALIA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('186', '比利时邮政', 'BEL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('187', 'BHT快递', 'BHT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('188', '秘鲁邮政', 'BILUYOUZHE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('189', '巴西邮政', 'BR');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('190', '不丹邮政', 'BUDANYOUZH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('191', 'CDEK', 'CDEK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('192', '加拿大邮政', 'CA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('193', '递必易国际物流', 'DBYWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('194', '大道物流', 'DDWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('195', '德国云快递', 'DGYKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('196', '到乐国际', 'DLGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('197', 'DHL德国', 'DHL_DE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('198', 'DHL(英文版)', 'DHL_EN');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('199', 'DHL全球', 'DHL_GLB');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('200', 'DHL Global Mail', 'DHLGM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('201', '丹麦邮政', 'DK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('202', 'DPD', 'DPD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('203', 'DPEX', 'DPEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('204', 'EMS国际', 'EMSGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('205', '易客满', 'EKM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('206', 'EPS (联众国际快运)', 'EPS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('207', 'EShipper', 'ESHIPPER');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('208', '丰程物流', 'FCWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('209', '法翔速运', 'FX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('210', 'FQ', 'FQ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('211', '国际e邮宝', 'GJEYB');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('212', '国际邮政包裹', 'GJYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('213', 'GE2D', 'GE2D');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('214', '冠泰', 'GT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('215', 'GLS', 'GLS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('216', '安的列斯群岛邮政', 'IADLSQDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('217', '欧洲专线(邮政)', 'IOZYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('218', '澳大利亚邮政', 'IADLYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('219', '阿尔巴尼亚邮政', 'IAEBNYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('220', '阿尔及利亚邮政', 'IAEJLYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('221', '阿富汗邮政', 'IAFHYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('222', '安哥拉邮政', 'IAGLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('223', '阿根廷邮政', 'IAGTYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('224', '埃及邮政', 'IAJYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('225', '阿鲁巴邮政', 'IALBYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('226', '奥兰群岛邮政', 'IALQDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('227', '阿联酋邮政', 'IALYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('228', '阿曼邮政', 'IAMYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('229', '阿塞拜疆邮政', 'IASBJYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('230', '爱沙尼亚邮政', 'IASNYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('231', '博茨瓦纳邮政', 'IBCWNYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('232', '波多黎各邮政', 'IBDLGYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('233', '冰岛邮政', 'IBDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('234', '白俄罗斯邮政', 'IBELSYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('235', '波黑邮政', 'IBHYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('236', '保加利亚邮政', 'IBJLYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('237', '巴基斯坦邮政', 'IBJSTYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('238', '黎巴嫩邮政', 'IBLNYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('239', '便利速递', 'IBLSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('240', '玻利维亚邮政', 'IBLWYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('241', '百慕达邮政', 'IBMDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('242', '波兰邮政', 'IBOLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('243', '宝通达', 'IBTD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('244', '贝邮宝', 'IBYB');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('245', '出口易', 'ICKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('246', '达方物流', 'IDFWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('247', '德国邮政', 'IDGYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('248', '危地马拉邮政', 'IWDMLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('249', '乌干达邮政', 'IWGDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('250', '乌克兰EMS', 'IWKLEMS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('251', '乌克兰邮政', 'IWKLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('252', '乌拉圭邮政', 'IWLGYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('253', '林克快递', 'ILKKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('254', '文莱邮政', 'IWLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('255', '新喀里多尼亚邮政', 'IXGLDNYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('256', '爱尔兰邮政', 'IE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('257', '夏浦物流', 'IXPWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('258', '叙利亚邮政', 'IXLYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('259', '印度邮政', 'IYDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('260', '夏浦世纪', 'IXPSJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('261', '厄瓜多尔邮政', 'IEGDEYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('262', '俄罗斯邮政', 'IELSYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('263', '厄立特里亚邮政', 'IELTLYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('264', '飞特物流', 'IFTWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('265', '瓜德罗普岛邮政', 'IGDLPDYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('266', '哥斯达黎加邮政', 'IGSDLJYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('267', '韩国邮政', 'IHGYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('268', '华翰物流', 'IHHWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('269', '互联易', 'IHLY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('270', '哈萨克斯坦邮政', 'IHSKSTYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('271', '黑山邮政', 'IHSYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('272', '津巴布韦邮政', 'IJBBWYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('273', '吉尔吉斯斯坦邮政', 'IJEJSSTYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('274', '捷克邮政', 'IJKYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('275', '加纳邮政', 'IJNYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('276', '柬埔寨邮政', 'IJPZYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('277', '克罗地亚邮政', 'IKNDYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('278', '肯尼亚邮政', 'IKNYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('279', '科特迪瓦EMS', 'IKTDWEMS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('280', '科特迪瓦邮政', 'IKTDWYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('281', '罗马尼亚邮政', 'ILMNYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('282', '摩尔多瓦邮政', 'IMEDWYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('283', '马耳他邮政', 'IMETYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('284', '尼日利亚邮政', 'INRLYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('285', '塞尔维亚邮政', 'ISEWYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('286', '塞浦路斯邮政', 'ISPLSYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('287', '乌兹别克斯坦邮政', 'IWZBKSTYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('288', '西班牙邮政', 'IXBYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('289', '新加坡EMS', 'IXJPEMS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('290', '希腊邮政', 'IXLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('291', '新西兰邮政', 'IXXLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('292', '意大利邮政', 'IYDLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('293', '英国邮政', 'IYGYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('294', '亚美尼亚邮政', 'IYMNYYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('295', '也门邮政', 'IYMYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('296', '智利邮政', 'IZLYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('297', '日本邮政', 'JP');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('298', '今枫国际', 'JFGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('299', '极光转运', 'JGZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('300', '吉祥邮转运', 'JXYKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('301', '嘉里国际', 'JLDT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('302', '绝配国际速递', 'JPKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('303', '佳惠尔', 'SYJHE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('304', '联运通', 'LYT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('305', '联合快递', 'LHKDS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('306', '林道国际', 'SHLDHY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('307', '荷兰邮政', 'NL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('308', '新顺丰', 'NSF');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('309', 'ONTRAC', 'ONTRAC');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('310', 'OCS', 'OCS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('311', '全球邮政', 'QQYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('312', 'POSTEIBE', 'POSTEIBE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('313', '啪啪供应链', 'PAPA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('314', '秦远海运', 'QYHY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('315', '启辰国际', 'VENUCIA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('316', '瑞典邮政', 'RDSE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('317', 'SKYPOST', 'SKYPOST');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('318', '瑞士邮政', 'SWCH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('319', '首达速运', 'SDSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('320', '穗空物流', 'SK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('321', '首通快运', 'STONG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('322', '申通快递国际单', 'STO_INTL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('323', '上海久易国际', 'JYSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('324', '泰国138', 'TAILAND138');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('325', 'USPS美国邮政', 'USPS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('326', '万国邮政', 'UPU');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('327', '中越国际物流', 'VCTRANS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('328', '星空国际', 'XKGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('329', '迅达国际', 'XD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('330', '香港邮政', 'XGYZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('331', '喜来快递', 'XLKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('332', '鑫世锐达', 'XSRD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('333', '新元国际', 'XYGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('334', 'ADLER雄鹰国际速递', 'XYGJSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('335', '日本大和运输(Yamato)', 'YAMA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('336', 'YODEL', 'YODEL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('337', '一号线', 'YHXGJSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('338', '约旦邮政', 'YUEDANYOUZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('339', '玥玛速运', 'YMSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('340', '鹰运', 'YYSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('341', '易境达', 'YJD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('342', '洋包裹', 'YBG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('343', '', '');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('344', 'AOL（澳通）', 'AOL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('345', 'BCWELT   ', 'BCWELT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('346', '笨鸟国际', 'BN');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('347', '优邦国际速运', 'UBONEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('348', 'UEX   ', 'UEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('349', '韵达国际', 'YDGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('350', '爱购转运', 'ZY_AG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('351', '爱欧洲', 'ZY_AOZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('352', '澳世速递', 'ZY_AUSE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('353', 'AXO', 'ZY_AXO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('354', '贝海速递', 'ZY_BH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('355', '八达网', 'ZY_BDA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('356', '蜜蜂速递', 'ZY_BEE');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('357', '百利快递', 'ZY_BL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('358', '斑马物流', 'ZY_BM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('359', '百通物流', 'ZY_BT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('360', '策马转运', 'ZY_CM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('361', 'EFS POST', 'ZY_EFS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('362', '宜送转运', 'ZY_ESONG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('363', 'ETD', 'ZY_ETD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('364', '飞碟快递', 'ZY_FD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('365', '飞鸽快递', 'ZY_FG');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('366', '风行快递', 'ZY_FX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('367', '风行速递', 'ZY_FXSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('368', '飞洋快递', 'ZY_FY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('369', '皓晨快递', 'ZY_HC');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('370', '华兴速运', 'ZY_HXSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('371', '海悦速递', 'ZY_HYSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('372', '君安快递', 'ZY_JA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('373', '时代转运', 'ZY_JD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('374', '骏达快递', 'ZY_JDKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('375', '骏达转运', 'ZY_JDZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('376', '久禾快递', 'ZY_JH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('377', '金海淘', 'ZY_JHT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('378', '联邦转运FedRoad', 'ZY_LBZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('379', '领跑者快递', 'ZY_LPZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('380', '赤兔马转运', 'ZY_CTM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('381', '龙象快递', 'ZY_LX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('382', '量子物流', 'ZY_LZWL');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('383', '美国转运', 'ZY_MGZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('384', '美速通', 'ZY_MST');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('385', '美西转运', 'ZY_MXZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('386', 'QQ-EX', 'ZY_QQEX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('387', '瑞天快递', 'ZY_RT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('388', '瑞天速递', 'ZY_RTSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('389', '速达快递', 'ZY_SDKD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('390', '四方转运', 'ZY_SFZY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('391', '上腾快递', 'ZY_ST');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('392', '天际快递', 'ZY_TJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('393', '天马转运', 'ZY_TM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('394', '滕牛快递', 'ZY_TN');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('395', 'TrakPak', 'ZY_TPAK');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('396', '太平洋快递', 'ZY_TPY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('397', '唐三藏转运', 'ZY_TSZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('398', 'TWC转运世界', 'ZY_TWC');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('399', '润东国际快线', 'ZY_RDGJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('400', '同心快递', 'ZY_TX');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('401', '天翼快递', 'ZY_TY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('402', '败欧洲', 'ZY_BOZ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('403', '德国海淘之家', 'ZY_DGHT');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('404', '德运网', 'ZY_DYW');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('405', '文达国际DCS', 'ZY_WDCS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('406', '同舟快递', 'ZY_TZH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('407', 'UCS合众快递', 'ZY_UCS');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('408', '星辰快递', 'ZY_XC');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('409', '先锋快递', 'ZY_XF');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('410', '西邮寄', 'ZY_XIYJ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('411', '云骑快递', 'ZY_YQ');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('412', '优晟速递', 'ZY_YSSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('413', '运淘美国', 'ZY_YTUSA');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('414', '至诚速递', 'ZY_ZCSD');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('415', '增速海淘', 'ZYZOOM');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('416', '中驰物流', 'ZH');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('417', '中欧快运', 'ZO');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('418', '准实快运', 'ZSKY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('419', '中外速运', 'ZWSY');
INSERT INTO `ims_superdesk_shop_express_kdniao` VALUES ('420', '郑州建华', 'ZZJH');

-- ----------------------------
-- Table structure for ims_superdesk_shop_express_kuaidi100
-- ----------------------------
DROP TABLE IF EXISTS `ims_superdesk_shop_express_kuaidi100`;
CREATE TABLE `ims_superdesk_shop_express_kuaidi100` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT '',
  `express` varchar(50) DEFAULT '',
  `status` tinyint(1) DEFAULT '1',
  `displayorder` tinyint(3) unsigned DEFAULT '0',
  `code` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ims_superdesk_shop_express_kuaidi100
-- ----------------------------
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('1', '顺丰', 'shunfeng', '1', '0', 'JH_014');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('2', '申通', 'shentong', '1', '0', 'JH_005');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('3', '韵达快运', 'yunda', '1', '0', 'JH_003');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('4', '天天快递', 'tiantian', '1', '0', 'JH_004');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('5', '圆通速递', 'yuantong', '1', '0', 'JH_002');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('6', '中通速递', 'zhongtong', '1', '0', 'JH_006');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('7', 'ems快递', 'ems', '1', '0', 'JH_001');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('8', '百世汇通', 'huitongkuaidi', '1', '0', 'JH_012');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('9', '全峰快递', 'quanfengkuaidi', '1', '0', 'JH_009');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('10', '宅急送', 'zhaijisong', '1', '0', 'JH_007');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('11', 'aae全球专递', 'aae', '1', '0', 'JHI_049');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('12', '安捷快递', 'anjie', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('13', '安信达快递', 'anxindakuaixi', '1', '0', 'JH_131');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('14', '彪记快递', 'biaojikuaidi', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('15', 'bht', 'bht', '1', '0', 'JHI_008');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('16', '百福东方国际物流', 'baifudongfang', '1', '0', 'JH_062');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('17', '中国东方（COE）', 'coe', '1', '0', 'JHI_038');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('18', '长宇物流', 'changyuwuliu', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('19', '大田物流', 'datianwuliu', '1', '0', 'JH_050');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('20', '德邦物流', 'debangwuliu', '1', '0', 'JH_011');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('21', 'dhl', 'dhl', '1', '0', 'JHI_002');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('22', 'dpex', 'dpex', '1', '0', 'JHI_011');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('23', 'd速快递', 'dsukuaidi', '1', '0', 'JH_049');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('24', '递四方', 'disifang', '1', '0', 'JHI_080');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('25', 'fedex（国外）', 'fedex', '1', '0', 'JHI_014');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('26', '飞康达物流', 'feikangda', '1', '0', 'JH_088');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('27', '凤凰快递', 'fenghuangkuaidi', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('28', '飞快达', 'feikuaida', '1', '0', 'JH_151');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('29', '国通快递', 'guotongkuaidi', '1', '0', 'JH_010');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('30', '港中能达物流', 'ganzhongnengda', '1', '0', 'JH_033');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('31', '广东邮政物流', 'guangdongyouzhengwuliu', '1', '0', 'JH_135');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('32', '共速达', 'gongsuda', '1', '0', 'JH_039');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('33', '恒路物流', 'hengluwuliu', '1', '0', 'JH_048');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('34', '华夏龙物流', 'huaxialongwuliu', '1', '0', 'JH_129');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('35', '海红', 'haihongwangsong', '1', '0', 'JH_132');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('36', '海外环球', 'haiwaihuanqiu', '1', '0', 'JHI_013');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('37', '佳怡物流', 'jiayiwuliu', '1', '0', 'JH_035');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('38', '京广速递', 'jinguangsudikuaijian', '1', '0', 'JH_041');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('39', '急先达', 'jixianda', '1', '0', 'JH_040');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('40', '佳吉物流', 'jiajiwuliu', '1', '0', 'JH_030');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('41', '加运美物流', 'jymwl', '1', '0', 'JH_054');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('42', '金大物流', 'jindawuliu', '1', '0', 'JH_079');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('43', '嘉里大通', 'jialidatong', '1', '0', 'JH_060');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('44', '晋越快递', 'jykd', '1', '0', 'JHI_046');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('45', '快捷速递', 'kuaijiesudi', '1', '0', 'JH_008');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('46', '联邦快递（国内）', 'lianb', '1', '0', 'JH_122');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('47', '联昊通物流', 'lianhaowuliu', '1', '0', 'JH_021');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('48', '龙邦物流', 'longbanwuliu', '1', '0', 'JH_019');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('49', '立即送', 'lijisong', '1', '0', 'JH_044');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('50', '乐捷递', 'lejiedi', '1', '0', 'JH_043');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('51', '民航快递', 'minghangkuaidi', '1', '0', 'JH_100');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('52', '美国快递', 'meiguokuaidi', '1', '0', 'JHI_044');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('53', '门对门', 'menduimen', '1', '0', 'JH_036');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('54', 'OCS', 'ocs', '1', '0', 'JHI_012');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('55', '配思货运', 'peisihuoyunkuaidi', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('56', '全晨快递', 'quanchenkuaidi', '1', '0', 'JH_055');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('57', '全际通物流', 'quanjitong', '1', '0', 'JH_127');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('58', '全日通快递', 'quanritongkuaidi', '1', '0', 'JH_029');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('59', '全一快递', 'quanyikuaidi', '1', '0', 'JH_020');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('60', '如风达', 'rufengda', '1', '0', 'JH_017');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('61', '三态速递', 'santaisudi', '1', '0', 'JH_065');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('62', '盛辉物流', 'shenghuiwuliu', '1', '0', 'JH_066');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('63', '速尔物流', 'sue', '1', '0', 'JH_016');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('64', '盛丰物流', 'shengfeng', '1', '0', 'JH_082');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('65', '赛澳递', 'saiaodi', '1', '0', 'JH_042');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('66', '天地华宇', 'tiandihuayu', '1', '0', 'JH_018');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('67', 'tnt', 'tnt', '1', '0', 'JHI_003');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('68', 'ups', 'ups', '1', '0', 'JHI_004');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('69', '万家物流', 'wanjiawuliu', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('70', '文捷航空速递', 'wenjiesudi', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('71', '伍圆', 'wuyuan', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('72', '万象物流', 'wxwl', '1', '0', 'JH_115');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('73', '新邦物流', 'xinbangwuliu', '1', '0', 'JH_022');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('74', '信丰物流', 'xinfengwuliu', '1', '0', 'JH_023');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('75', '亚风速递', 'yafengsudi', '1', '0', 'JH_075');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('76', '一邦速递', 'yibangwuliu', '1', '0', 'JH_064');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('77', '优速物流', 'youshuwuliu', '1', '0', 'JH_013');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('78', '邮政快递包裹', 'youzhengguonei', '1', '0', 'JH_077');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('79', '邮政国际包裹挂号信', 'youzhengguoji', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('80', '远成物流', 'yuanchengwuliu', '1', '0', 'JH_024');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('81', '源伟丰快递', 'yuanweifeng', '1', '0', 'JH_141');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('82', '元智捷诚快递', 'yuanzhijiecheng', '1', '0', 'JH_126');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('83', '运通快递', 'yuntongkuaidi', '1', '0', 'JH_145');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('84', '越丰物流', 'yuefengwuliu', '1', '0', 'JH_068');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('85', '源安达', 'yad', '1', '0', 'JH_067');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('86', '银捷速递', 'yinjiesudi', '1', '0', 'JH_148');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('87', '中铁快运', 'zhongtiekuaiyun', '1', '0', 'JH_015');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('88', '中邮物流', 'zhongyouwuliu', '1', '0', 'JH_027');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('89', '忠信达', 'zhongxinda', '1', '0', 'JH_086');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('90', '芝麻开门', 'zhimakaimen', '1', '0', 'JH_026');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('91', '安能物流', 'annengwuliu', '1', '0', 'JH_059');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('92', '京东快递', 'jd', '1', '0', 'JH_046');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('93', '微特派', 'weitepai', '1', '0', '');
INSERT INTO `ims_superdesk_shop_express_kuaidi100` VALUES ('94', '九曳供应链', 'jiuyescm', '1', '0', '');
