--
-- 表的结构 `ims_superdesk_shop_goods`
--

CREATE TABLE IF NOT EXISTS `ims_superdesk_shop_goods` (
  `id` int(11) NOT NULL COMMENT 'ID',
  `uniacid` int(11) DEFAULT '0',
  `pcate` int(11) DEFAULT '0' COMMENT '一级分类ID',
  `ccate` int(11) DEFAULT '0' COMMENT '二级分类ID',
  `tcate` int(11) DEFAULT '0' COMMENT '三级分类ID',
  `type` tinyint(1) DEFAULT '1' COMMENT '类型 1 实体物品 2 虚拟物品 3 虚拟物品(卡密) 4 批发 10 话费流量充值 20 充值卡',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态 0 下架 1 上架 2 赠品上架',
  `displayorder` int(11) DEFAULT '0' COMMENT '显示顺序',
  `title` varchar(100) DEFAULT '' COMMENT '商品名称',
  `thumb` varchar(255) DEFAULT '' COMMENT '商品图',
  `unit` varchar(5) DEFAULT '' COMMENT '商品单位',
  `description` varchar(1000) DEFAULT NULL COMMENT '分享描述',
  `content` text COMMENT '商品详情',
  `goodssn` varchar(50) DEFAULT '' COMMENT '商品编号',
  `productsn` varchar(50) DEFAULT '' COMMENT '商品条码',
  `productprice` decimal(10,2) DEFAULT '0.00' COMMENT '商品原价',
  `marketprice` decimal(10,2) DEFAULT '0.00' COMMENT '商品现价',
  `costprice` decimal(10,2) DEFAULT '0.00' COMMENT '商品成本',
  `originalprice` decimal(10,2) DEFAULT '0.00' COMMENT '原价 好象已经废弃',
  `total` int(10) DEFAULT '0' COMMENT '商品库存',
  `totalcnf` int(11) DEFAULT '0' COMMENT '减库存方式 0 拍下减库存 1 付款减库存 2 永不减库存',
  `sales` int(11) DEFAULT '0' COMMENT '已出售数',
  `salesreal` int(11) DEFAULT '0' COMMENT '实际售出数',
  `spec` varchar(5000) DEFAULT '' COMMENT '商品规格设置',
  `createtime` int(11) DEFAULT '0' COMMENT '建立时间',
  `weight` decimal(10,2) DEFAULT '0.00' COMMENT '重量(单位g)',
  `credit` varchar(255) DEFAULT NULL COMMENT '购买赠送积分，如果带%号，则为按成交价比例计算',
  `maxbuy` int(11) DEFAULT '0' COMMENT '单次最多购买量',
  `usermaxbuy` int(11) DEFAULT '0' COMMENT '用户最多购买量',
  `hasoption` int(11) DEFAULT '0' COMMENT '启用商品规则 0 不启用 1 启用',
  `dispatch` int(11) DEFAULT '0' COMMENT '配送',
  `thumb_url` text COMMENT '缩略图地址',
  `isnew` tinyint(1) DEFAULT '0' COMMENT '新上',
  `ishot` tinyint(1) DEFAULT '0' COMMENT '热卖',
  `isdiscount` tinyint(1) DEFAULT '0' COMMENT '促销',
  `isrecommand` tinyint(1) DEFAULT '0' COMMENT '推荐',
  `issendfree` tinyint(1) DEFAULT '0' COMMENT '包邮',
  `istime` tinyint(1) DEFAULT '0' COMMENT '限时卖',
  `iscomment` tinyint(1) DEFAULT '0' COMMENT '允许评价',
  `timestart` int(11) DEFAULT '0' COMMENT '限卖开始时间',
  `timeend` int(11) DEFAULT '0' COMMENT '限卖结束时间',
  `viewcount` int(11) DEFAULT '0' COMMENT '查看次数',
  `deleted` tinyint(3) DEFAULT '0' COMMENT '是否删除',
  `hascommission` tinyint(3) DEFAULT '0' COMMENT '是否有分销',
  `commission1_rate` decimal(10,2) DEFAULT '0.00' COMMENT '一级分销比率',
  `commission1_pay` decimal(10,2) DEFAULT '0.00' COMMENT '一级分销固定佣金',
  `commission2_rate` decimal(10,2) DEFAULT '0.00' COMMENT '二级分销比率',
  `commission2_pay` decimal(10,2) DEFAULT '0.00' COMMENT '二级分销固定佣金',
  `commission3_rate` decimal(10,2) DEFAULT '0.00' COMMENT '三级分销比率',
  `commission3_pay` decimal(10,2) DEFAULT '0.00' COMMENT '三级分销固定佣金',
  `score` decimal(10,2) DEFAULT '0.00' COMMENT '得分 好象已经废弃',
  `taobaoid` varchar(255) DEFAULT '' COMMENT '淘宝ID 淘宝助手',
  `taotaoid` varchar(255) DEFAULT '' COMMENT '淘宝ID 淘宝助手',
  `taobaourl` varchar(255) DEFAULT '' COMMENT '淘宝网址 淘宝助手',
  `updatetime` int(11) DEFAULT '0' COMMENT '更新时间',
  `share_title` varchar(255) DEFAULT '' COMMENT '分享标题',
  `share_icon` varchar(255) DEFAULT '' COMMENT '分享图标',
  `cash` tinyint(3) DEFAULT '0' COMMENT '企业月结 1 不支持 2 支持',
  `commission_thumb` varchar(255) DEFAULT '' COMMENT '海报图片',
  `isnodiscount` tinyint(3) DEFAULT '0' COMMENT '不参与会员折扣',
  `showlevels` text COMMENT '浏览权限',
  `buylevels` text COMMENT '购买权限',
  `showgroups` text COMMENT '会员组浏览权限',
  `buygroups` text COMMENT '会员组购买权限',
  `isverify` tinyint(3) DEFAULT '0' COMMENT '支持线下核销 Null 0 1 不支持 2 支持',
  `storeids` text COMMENT '支持门店ID',
  `noticeopenid` varchar(255) DEFAULT '' COMMENT '商家通知',
  `noticetype` text COMMENT '提醒类型',
  `needfollow` tinyint(3) DEFAULT '0' COMMENT '需要关注',
  `followtip` varchar(255) DEFAULT '' COMMENT '关注事项',
  `followurl` varchar(255) DEFAULT '' COMMENT '关注地址',
  `deduct` decimal(10,2) DEFAULT '0.00',
  `virtual` int(11) DEFAULT '0' COMMENT '虚拟商品模板ID 0 多规格虚拟商品',
  `ccates` text COMMENT '一级多重分类',
  `discounts` text COMMENT '折扣',
  `nocommission` tinyint(3) DEFAULT '0' COMMENT '不执行分销',
  `hidecommission` tinyint(3) DEFAULT '0' COMMENT '隐藏分销按钮',
  `pcates` text COMMENT '二级多重分类',
  `cates` text COMMENT '多重分类数据集',
  `tcates` text COMMENT '三级多重分类',
  `artid` int(11) DEFAULT '0' COMMENT '营销文章ID',
  `detail_logo` varchar(255) DEFAULT '' COMMENT '店铺LOGO',
  `detail_shopname` varchar(255) DEFAULT '' COMMENT '店铺名称',
  `detail_btntext1` varchar(255) DEFAULT '' COMMENT '按钮1名称',
  `detail_btnurl1` varchar(255) DEFAULT '' COMMENT '按钮1链接 默认"查看所有商品"及"默认的全部商品连接"',
  `detail_btntext2` varchar(255) DEFAULT '' COMMENT '按钮2名称',
  `detail_btnurl2` varchar(255) DEFAULT '' COMMENT '按钮2链接 默认"进店逛逛"及"默认的小店或商城连接"',
  `detail_totaltitle` varchar(255) DEFAULT '' COMMENT '全部宝贝x个',
  `deduct2` decimal(10,2) DEFAULT '0.00' COMMENT '余额抵扣 0 支持全额抵扣 -1 不支持余额抵扣 >0 最多抵扣 元',
  `ednum` int(11) DEFAULT '0' COMMENT '单品满件包邮 0 : 不支持满件包邮',
  `edmoney` decimal(10,2) DEFAULT '0.00' COMMENT '单品满额包邮 0 : 不支持满额包邮',
  `edareas` text COMMENT '不参加满包邮的地区 ，0 : 不支持满件包邮',
  `diyformtype` tinyint(1) DEFAULT '0' COMMENT '自定义表单类型 0 关闭 1 附加形式 2 替换模式',
  `diyformid` int(11) DEFAULT '0' COMMENT '自定义表单ID',
  `diymode` tinyint(1) DEFAULT '0' COMMENT '自定义表单模式 0 系统默认 1 点击立即购买时填写 2 确认订单时填写',
  `dispatchtype` tinyint(1) DEFAULT '0' COMMENT '配送类型 0 运费模板 1 统一邮费',
  `dispatchid` int(11) DEFAULT '0' COMMENT '配送ID',
  `dispatchprice` decimal(10,2) DEFAULT '0.00' COMMENT '统一邮费',
  `manydeduct` tinyint(1) DEFAULT '0' COMMENT '多件累计抵扣积分',
  `shorttitle` varchar(255) DEFAULT '' COMMENT '短名称 打印需要',
  `isdiscount_title` varchar(255) DEFAULT '' COMMENT 'v2 促销标题',
  `isdiscount_time` int(11) DEFAULT '0' COMMENT 'v2 促销结束时间',
  `isdiscount_discounts` text COMMENT 'v2 促销价格 数字为价格 百分数 为折扣',
  `commission` text COMMENT 'v2 分销',
  `shopid` int(11) DEFAULT '0' COMMENT 'v2 商户ID',
  `allcates` text COMMENT 'v2 好象无用',
  `minbuy` int(11) DEFAULT '0' COMMENT 'v2 用户单次必须购买数量',
  `minprice` decimal(10,2) DEFAULT '0.00' COMMENT 'v2 多规格中最小价格，无规格时显示销售价',
  `invoice` tinyint(3) DEFAULT '0' COMMENT 'v2 提供发票',
  `repair` tinyint(3) DEFAULT '0' COMMENT 'v2 保修',
  `seven` tinyint(3) DEFAULT '0' COMMENT 'v2 7天无理由退换',
  `money` varchar(255) DEFAULT '' COMMENT 'v2 余额返现',
  `maxprice` decimal(10,2) DEFAULT '0.00' COMMENT 'v2 多规格中最大价格，无规格时显示销售价',
  `province` varchar(255) DEFAULT '' COMMENT 'v2 商品所在省 如为空则显示商城所在',
  `city` varchar(255) DEFAULT '' COMMENT 'v2 商品所在城市 如为空则显示商城所在',
  `buyshow` tinyint(1) DEFAULT '0' COMMENT 'v2 购买后可见 0 关闭 1 开启',
  `buycontent` text COMMENT 'v2 购买可见开启后的内容',
  `virtualsend` tinyint(1) DEFAULT '0' COMMENT 'v2 自动发货 0 否 1 是 ，注：自动发货后，订单自动完成',
  `virtualsendcontent` text COMMENT 'v2 自动发货内容',
  `verifytype` tinyint(1) DEFAULT '0' COMMENT 'v2 核销类型 0 按订单核销 1 按次核销 2 按消费码核销',
  `diyfields` text COMMENT 'v2',
  `diysaveid` int(11) DEFAULT '0' COMMENT 'v2',
  `diysave` tinyint(1) DEFAULT '0' COMMENT 'v2',
  `quality` tinyint(3) DEFAULT '0' COMMENT 'v2 正品保证',
  `groupstype` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'v2 是否支持拼团 0 否 1 支持',
  `showtotal` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'v2 显示库存 0 不显示 1 显示',
  `subtitle` varchar(255) DEFAULT '' COMMENT 'v2 子标题',
  `sharebtn` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'v2 分享按钮链接方式 0 弹出关注提示层 1 跳转至商品海报',
  `merchid` int(11) DEFAULT '0' COMMENT 'v2 商户ID',
  `checked` tinyint(3) DEFAULT '0' COMMENT 'v2 审核状态',
  `thumb_first` tinyint(3) DEFAULT '0' COMMENT 'v2 详情页面显示首图 0 不显示 1 显示 注：首图为列表页使用，尺寸较小',
  `catesinit3` text COMMENT 'v2 是否初始化分类信息 标识字段无用',
  `showtotaladd` tinyint(1) DEFAULT '0' COMMENT 'v2 是否调整过显示库存 标识字段无用',
  `merchsale` tinyint(1) DEFAULT '0' COMMENT 'v2 手机端使用的价格 0 当前设置促销价格 1 商户设置促销价格',
  `keywords` varchar(255) DEFAULT '' COMMENT 'v2 关键词',
  `catch_id` varchar(255) DEFAULT '' COMMENT 'v2 抓取产品信息ID',
  `catch_url` varchar(255) DEFAULT '' COMMENT 'v2 抓取产品地址',
  `catch_source` varchar(255) DEFAULT '' COMMENT 'v2 抓取产品来源',
  `minpriceupdated` tinyint(1) DEFAULT '0' COMMENT 'v2 是否更新过价格 标识字段无用',
  `labelname` text COMMENT 'v2 商品标签',
  `autoreceive` int(11) DEFAULT '0' COMMENT 'v2 自动收货 0 系统设置 -1 不自动收货 >0 天数',
  `cannotrefund` tinyint(3) DEFAULT '0' COMMENT 'v2 不允许退货',
  `bargain` int(11) DEFAULT '0' COMMENT 'v2 砍价',
  `buyagain` decimal(10,2) DEFAULT '0.00' COMMENT 'v2 重复购买折扣',
  `buyagain_islong` tinyint(1) DEFAULT '0' COMMENT 'v2 购买一次后,以后都使用这个折扣 0 否 1 是',
  `buyagain_condition` tinyint(1) DEFAULT '0' COMMENT 'v2 使用条件 0 付款后 1 完成后',
  `buyagain_sale` tinyint(1) DEFAULT '0' COMMENT 'v2 可否使用优惠 （重复购买时,是否与其他优惠共享!其他优惠享受后,再使用这个折扣）',
  `buyagain_commission` text COMMENT 'v2 复购分销',
  `diypage` int(11) DEFAULT NULL COMMENT 'v2 自定义页面ID',
  `saleupdate32484` tinyint(3) DEFAULT '0',
  `saleupdate33219` tinyint(3) DEFAULT '0',
  `saleupdate35843` tinyint(3) DEFAULT '0',
  `saleupdate36586` tinyint(3) DEFAULT '0',
  `saleupdate37975` tinyint(3) DEFAULT '0',
  `saleupdate40170` tinyint(3) DEFAULT '0',
  `saleupdate51117` tinyint(3) DEFAULT '0',
  `saleupdate53481` tinyint(3) DEFAULT '0'
) ENGINE=MyISAM AUTO_INCREMENT=200 DEFAULT CHARSET=utf8;

--
-- 转存表中的数据 `ims_superdesk_shop_goods`
--

INSERT INTO `ims_superdesk_shop_goods` (`id`, `uniacid`, `pcate`, `ccate`, `tcate`, `type`, `status`, `displayorder`, `title`, `thumb`, `unit`, `description`, `content`, `goodssn`, `productsn`, `productprice`, `marketprice`, `costprice`, `originalprice`, `total`, `totalcnf`, `sales`, `salesreal`, `spec`, `createtime`, `weight`, `credit`, `maxbuy`, `usermaxbuy`, `hasoption`, `dispatch`, `thumb_url`, `isnew`, `ishot`, `isdiscount`, `isrecommand`, `issendfree`, `istime`, `iscomment`, `timestart`, `timeend`, `viewcount`, `deleted`, `hascommission`, `commission1_rate`, `commission1_pay`, `commission2_rate`, `commission2_pay`, `commission3_rate`, `commission3_pay`, `score`, `taobaoid`, `taotaoid`, `taobaourl`, `updatetime`, `share_title`, `share_icon`, `cash`, `commission_thumb`, `isnodiscount`, `showlevels`, `buylevels`, `showgroups`, `buygroups`, `isverify`, `storeids`, `noticeopenid`, `noticetype`, `needfollow`, `followtip`, `followurl`, `deduct`, `virtual`, `ccates`, `discounts`, `nocommission`, `hidecommission`, `pcates`, `cates`, `tcates`, `artid`, `detail_logo`, `detail_shopname`, `detail_btntext1`, `detail_btnurl1`, `detail_btntext2`, `detail_btnurl2`, `detail_totaltitle`, `deduct2`, `ednum`, `edmoney`, `edareas`, `diyformtype`, `diyformid`, `diymode`, `dispatchtype`, `dispatchid`, `dispatchprice`, `manydeduct`, `shorttitle`, `isdiscount_title`, `isdiscount_time`, `isdiscount_discounts`, `commission`, `shopid`, `allcates`, `minbuy`, `minprice`, `invoice`, `repair`, `seven`, `money`, `maxprice`, `province`, `city`, `buyshow`, `buycontent`, `virtualsend`, `virtualsendcontent`, `verifytype`, `diyfields`, `diysaveid`, `diysave`, `quality`, `groupstype`, `showtotal`, `subtitle`, `sharebtn`, `merchid`, `checked`, `thumb_first`, `catesinit3`, `showtotaladd`, `merchsale`, `keywords`, `catch_id`, `catch_url`, `catch_source`, `minpriceupdated`, `labelname`, `autoreceive`, `cannotrefund`, `bargain`, `buyagain`, `buyagain_islong`, `buyagain_condition`, `buyagain_sale`, `buyagain_commission`, `diypage`, `saleupdate32484`, `saleupdate33219`, `saleupdate35843`, `saleupdate36586`, `saleupdate37975`, `saleupdate40170`, `saleupdate51117`, `saleupdate53481`) VALUES
(199, 16, 1, 0, 0, 1, 1, 0, '商品名称avic_jdbbuy', 'images/16/2017/09/FPoS8y6TrTEo3hvEen338v3UvUE3Uq.jpg', '', '', '', '', '', '2.00', '1.00', '0.00', '0.00', 999, 0, 1, 0, '', 1509971361, '0.00', '', 0, 0, 0, 0, 'a:0:{}', 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '', '', '', 0, '', '', 0, '', 0, '', '', '', '', 1, '', '', '0', 0, '', '', '0.00', 0, '', '{"type":"0","default":"0","default_pay":"0"}', 0, 0, '1', '1', '', 0, '', '', '', '', '', '', '', '0.00', 0, '0.00', '', 1, 2, 0, 0, 0, '0.00', 0, '', '', 1509971280, '{"type":0,"default":{"option0":""},"merch":{"option0":""}}', '{"type":0}', 0, NULL, 0, '1.00', 1, 1, 1, '', '1.00', '广东省', '深圳市', 0, '', 0, '', 0, NULL, 0, 0, 1, 0, 1, '商品名称avic_jdbbuy', 0, 1, 0, 0, NULL, 0, 1, '', '', '', '', 0, 'null', 0, 0, 0, '0.00', 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ims_superdesk_shop_goods`
--
ALTER TABLE `ims_superdesk_shop_goods`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_uniacid` (`uniacid`),
  ADD KEY `idx_pcate` (`pcate`),
  ADD KEY `idx_ccate` (`ccate`),
  ADD KEY `idx_isnew` (`isnew`),
  ADD KEY `idx_ishot` (`ishot`),
  ADD KEY `idx_isdiscount` (`isdiscount`),
  ADD KEY `idx_isrecommand` (`isrecommand`),
  ADD KEY `idx_iscomment` (`iscomment`),
  ADD KEY `idx_issendfree` (`issendfree`),
  ADD KEY `idx_istime` (`istime`),
  ADD KEY `idx_deleted` (`deleted`),
  ADD KEY `idx_tcate` (`tcate`),
  ADD KEY `idx_scate` (`tcate`),
  ADD KEY `idx_merchid` (`merchid`),
  ADD KEY `idx_checked` (`checked`),
  ADD FULLTEXT KEY `idx_buylevels` (`buylevels`);
ALTER TABLE `ims_superdesk_shop_goods`
  ADD FULLTEXT KEY `idx_showgroups` (`showgroups`);
ALTER TABLE `ims_superdesk_shop_goods`
  ADD FULLTEXT KEY `idx_buygroups` (`buygroups`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `ims_superdesk_shop_goods`
--
ALTER TABLE `ims_superdesk_shop_goods`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',AUTO_INCREMENT=200;

------------------------------------------ ims_superdesk_shop_goods ------------------------------------------

ALTER TABLE `ims_superdesk_shop_goods`
ADD `jd_vop_sku` INT(11) NOT NULL DEFAULT '0' AFTER `saleupdate53481`;

ALTER TABLE `ims_superdesk_shop_goods`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID' ,
CHANGE COLUMN `pcate` `pcate` INT(11) NULL DEFAULT '0' COMMENT '一级分类ID' ,
CHANGE COLUMN `ccate` `ccate` INT(11) NULL DEFAULT '0' COMMENT '二级分类ID' ,
CHANGE COLUMN `type` `type` TINYINT(1) NULL DEFAULT '1' COMMENT '类型 1 实体物品 2 虚拟物品 3 虚拟物品(卡密) 4 批发 10 话费流量充值 20 充值卡' ,
CHANGE COLUMN `status` `status` TINYINT(1) NULL DEFAULT '1' COMMENT '状态 0 下架 1 上架 2 赠品上架' ,
CHANGE COLUMN `displayorder` `displayorder` INT(11) NULL DEFAULT '0' COMMENT '显示顺序' ,
CHANGE COLUMN `title` `title` VARCHAR(100) NULL DEFAULT '' COMMENT '商品名称' ,
CHANGE COLUMN `thumb` `thumb` VARCHAR(255) NULL DEFAULT '' COMMENT '商品图' ,
CHANGE COLUMN `unit` `unit` VARCHAR(5) NULL DEFAULT '' COMMENT '商品单位' ,
CHANGE COLUMN `description` `description` VARCHAR(1000) NULL DEFAULT NULL COMMENT '分享描述' ,
CHANGE COLUMN `content` `content` TEXT NULL DEFAULT NULL COMMENT '商品详情' ,
CHANGE COLUMN `goodssn` `goodssn` VARCHAR(50) NULL DEFAULT '' COMMENT '商品编号' ,
CHANGE COLUMN `productsn` `productsn` VARCHAR(50) NULL DEFAULT '' COMMENT '商品条码' ,
CHANGE COLUMN `productprice` `productprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '商品原价' ,
CHANGE COLUMN `marketprice` `marketprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '商品现价' ,
CHANGE COLUMN `costprice` `costprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '商品成本' ,
CHANGE COLUMN `originalprice` `originalprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '原价 好象已经废弃' ,
CHANGE COLUMN `total` `total` INT(10) NULL DEFAULT '0' COMMENT '商品库存' ,
CHANGE COLUMN `totalcnf` `totalcnf` INT(11) NULL DEFAULT '0' COMMENT '减库存方式 0 拍下减库存 1 付款减库存 2 永不减库存' ,
CHANGE COLUMN `sales` `sales` INT(11) NULL DEFAULT '0' COMMENT '已出售数' ,
CHANGE COLUMN `salesreal` `salesreal` INT(11) NULL DEFAULT '0' COMMENT '实际售出数' ,
CHANGE COLUMN `spec` `spec` VARCHAR(5000) NULL DEFAULT '' COMMENT '商品规格设置' ,
CHANGE COLUMN `createtime` `createtime` INT(11) NULL DEFAULT '0' COMMENT '建立时间' ,
CHANGE COLUMN `weight` `weight` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '重量(单位g)' ,
CHANGE COLUMN `credit` `credit` VARCHAR(255) NULL DEFAULT NULL COMMENT '购买赠送积分，如果带%号，则为按成交价比例计算' ,
CHANGE COLUMN `maxbuy` `maxbuy` INT(11) NULL DEFAULT '0' COMMENT '单次最多购买量' ,
CHANGE COLUMN `usermaxbuy` `usermaxbuy` INT(11) NULL DEFAULT '0' COMMENT '用户最多购买量' ,
CHANGE COLUMN `hasoption` `hasoption` INT(11) NULL DEFAULT '0' COMMENT '启用商品规则 0 不启用 1 启用' ,
CHANGE COLUMN `dispatch` `dispatch` INT(11) NULL DEFAULT '0' COMMENT '配送' ,
CHANGE COLUMN `thumb_url` `thumb_url` TEXT NULL DEFAULT NULL COMMENT '缩略图地址' ,
CHANGE COLUMN `isnew` `isnew` TINYINT(1) NULL DEFAULT '0' COMMENT '新上' ,
CHANGE COLUMN `ishot` `ishot` TINYINT(1) NULL DEFAULT '0' COMMENT '热卖' ,
CHANGE COLUMN `isdiscount` `isdiscount` TINYINT(1) NULL DEFAULT '0' COMMENT '促销' ,
CHANGE COLUMN `isrecommand` `isrecommand` TINYINT(1) NULL DEFAULT '0' COMMENT '推荐' ,
CHANGE COLUMN `issendfree` `issendfree` TINYINT(1) NULL DEFAULT '0' COMMENT '包邮' ,
CHANGE COLUMN `istime` `istime` TINYINT(1) NULL DEFAULT '0' COMMENT '限时卖' ,
CHANGE COLUMN `iscomment` `iscomment` TINYINT(1) NULL DEFAULT '0' COMMENT '允许评价' ,
CHANGE COLUMN `timestart` `timestart` INT(11) NULL DEFAULT '0' COMMENT '限卖开始时间' ,
CHANGE COLUMN `timeend` `timeend` INT(11) NULL DEFAULT '0' COMMENT '限卖结束时间' ,
CHANGE COLUMN `viewcount` `viewcount` INT(11) NULL DEFAULT '0' COMMENT '查看次数' ,
CHANGE COLUMN `deleted` `deleted` TINYINT(3) NULL DEFAULT '0' COMMENT '是否删除' ,
CHANGE COLUMN `hascommission` `hascommission` TINYINT(3) NULL DEFAULT '0' COMMENT '是否有分销' ,
CHANGE COLUMN `commission1_rate` `commission1_rate` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '一级分销比率' ,
CHANGE COLUMN `commission1_pay` `commission1_pay` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '一级分销固定佣金' ,
CHANGE COLUMN `commission2_rate` `commission2_rate` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '二级分销比率' ,
CHANGE COLUMN `commission2_pay` `commission2_pay` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '二级分销固定佣金' ,
CHANGE COLUMN `commission3_rate` `commission3_rate` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '三级分销比率' ,
CHANGE COLUMN `commission3_pay` `commission3_pay` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '三级分销固定佣金' ,
CHANGE COLUMN `score` `score` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '得分 好象已经废弃' ,
CHANGE COLUMN `taobaoid` `taobaoid` VARCHAR(255) NULL DEFAULT '' COMMENT '淘宝ID 淘宝助手' ,
CHANGE COLUMN `taotaoid` `taotaoid` VARCHAR(255) NULL DEFAULT '' COMMENT '淘宝ID 淘宝助手' ,
CHANGE COLUMN `taobaourl` `taobaourl` VARCHAR(255) NULL DEFAULT '' COMMENT '淘宝网址 淘宝助手' ,
CHANGE COLUMN `updatetime` `updatetime` INT(11) NULL DEFAULT '0' COMMENT '更新时间' ,
CHANGE COLUMN `share_title` `share_title` VARCHAR(255) NULL DEFAULT '' COMMENT '分享标题' ,
CHANGE COLUMN `share_icon` `share_icon` VARCHAR(255) NULL DEFAULT '' COMMENT '分享图标' ,
CHANGE COLUMN `cash` `cash` TINYINT(3) NULL DEFAULT '0' COMMENT '企业月结 1 不支持 2 支持' ,
CHANGE COLUMN `commission_thumb` `commission_thumb` VARCHAR(255) NULL DEFAULT '' COMMENT '海报图片' ,
CHANGE COLUMN `isnodiscount` `isnodiscount` TINYINT(3) NULL DEFAULT '0' COMMENT '不参与会员折扣' ,
CHANGE COLUMN `showlevels` `showlevels` TEXT NULL DEFAULT NULL COMMENT '浏览权限' ,
CHANGE COLUMN `buylevels` `buylevels` TEXT NULL DEFAULT NULL COMMENT '购买权限' ,
CHANGE COLUMN `showgroups` `showgroups` TEXT NULL DEFAULT NULL COMMENT '会员组浏览权限' ,
CHANGE COLUMN `buygroups` `buygroups` TEXT NULL DEFAULT NULL COMMENT '会员组购买权限' ,
CHANGE COLUMN `isverify` `isverify` TINYINT(3) NULL DEFAULT '0' COMMENT '支持线下核销 Null 0 1 不支持 2 支持' ,
CHANGE COLUMN `storeids` `storeids` TEXT NULL DEFAULT NULL COMMENT '支持门店ID' ,
CHANGE COLUMN `noticeopenid` `noticeopenid` VARCHAR(255) NULL DEFAULT '' COMMENT '商家通知' ,
CHANGE COLUMN `tcate` `tcate` INT(11) NULL DEFAULT '0' COMMENT '三级分类ID' ,
CHANGE COLUMN `noticetype` `noticetype` TEXT NULL DEFAULT NULL COMMENT '提醒类型' ,
CHANGE COLUMN `needfollow` `needfollow` TINYINT(3) NULL DEFAULT '0' COMMENT '需要关注' ,
CHANGE COLUMN `followtip` `followtip` VARCHAR(255) NULL DEFAULT '' COMMENT '关注事项' ,
CHANGE COLUMN `followurl` `followurl` VARCHAR(255) NULL DEFAULT '' COMMENT '关注地址' ,
CHANGE COLUMN `virtual` `virtual` INT(11) NULL DEFAULT '0' COMMENT '虚拟商品模板ID 0 多规格虚拟商品' ,
CHANGE COLUMN `ccates` `ccates` TEXT NULL DEFAULT NULL COMMENT '一级多重分类' ,
CHANGE COLUMN `discounts` `discounts` TEXT NULL DEFAULT NULL COMMENT '折扣' ,
CHANGE COLUMN `nocommission` `nocommission` TINYINT(3) NULL DEFAULT '0' COMMENT '不执行分销' ,
CHANGE COLUMN `hidecommission` `hidecommission` TINYINT(3) NULL DEFAULT '0' COMMENT '隐藏分销按钮' ,
CHANGE COLUMN `pcates` `pcates` TEXT NULL DEFAULT NULL COMMENT '二级多重分类' ,
CHANGE COLUMN `tcates` `tcates` TEXT NULL DEFAULT NULL COMMENT '三级多重分类' ,
CHANGE COLUMN `artid` `artid` INT(11) NULL DEFAULT '0' COMMENT '营销文章ID' ,
CHANGE COLUMN `detail_logo` `detail_logo` VARCHAR(255) NULL DEFAULT '' COMMENT '店铺LOGO' ,
CHANGE COLUMN `detail_shopname` `detail_shopname` VARCHAR(255) NULL DEFAULT '' COMMENT '店铺名称' ,
CHANGE COLUMN `detail_btntext1` `detail_btntext1` VARCHAR(255) NULL DEFAULT '' COMMENT '按钮1名称' ,
CHANGE COLUMN `detail_btnurl1` `detail_btnurl1` VARCHAR(255) NULL DEFAULT '' COMMENT '按钮1链接 默认\"查看所有商品\"及\"默认的全部商品连接\"' ,
CHANGE COLUMN `detail_btntext2` `detail_btntext2` VARCHAR(255) NULL DEFAULT '' COMMENT '按钮2名称' ,
CHANGE COLUMN `detail_btnurl2` `detail_btnurl2` VARCHAR(255) NULL DEFAULT '' COMMENT '按钮2链接 默认\"进店逛逛\"及\"默认的小店或商城连接\"' ,
CHANGE COLUMN `detail_totaltitle` `detail_totaltitle` VARCHAR(255) NULL DEFAULT '' COMMENT '全部宝贝x个' ,
CHANGE COLUMN `cates` `cates` TEXT NULL DEFAULT NULL COMMENT '多重分类数据集' ,
CHANGE COLUMN `deduct2` `deduct2` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '余额抵扣 0 支持全额抵扣 -1 不支持余额抵扣 >0 最多抵扣 元' ,
CHANGE COLUMN `ednum` `ednum` INT(11) NULL DEFAULT '0' COMMENT '单品满件包邮 0 : 不支持满件包邮' ,
CHANGE COLUMN `edmoney` `edmoney` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '单品满额包邮 0 : 不支持满额包邮' ,
CHANGE COLUMN `edareas` `edareas` TEXT NULL DEFAULT NULL COMMENT '不参加满包邮的地区 ，0 : 不支持满件包邮' ,
CHANGE COLUMN `diyformtype` `diyformtype` TINYINT(1) NULL DEFAULT '0' COMMENT '自定义表单类型 0 关闭 1 附加形式 2 替换模式' ,
CHANGE COLUMN `diyformid` `diyformid` INT(11) NULL DEFAULT '0' COMMENT '自定义表单ID' ,
CHANGE COLUMN `diymode` `diymode` TINYINT(1) NULL DEFAULT '0' COMMENT '自定义表单模式 0 系统默认 1 点击立即购买时填写 2 确认订单时填写' ,
CHANGE COLUMN `dispatchtype` `dispatchtype` TINYINT(1) NULL DEFAULT '0' COMMENT '配送类型 0 运费模板 1 统一邮费' ,
CHANGE COLUMN `dispatchid` `dispatchid` INT(11) NULL DEFAULT '0' COMMENT '配送ID' ,
CHANGE COLUMN `dispatchprice` `dispatchprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '统一邮费' ,
CHANGE COLUMN `manydeduct` `manydeduct` TINYINT(1) NULL DEFAULT '0' COMMENT '多件累计抵扣积分' ,
CHANGE COLUMN `shorttitle` `shorttitle` VARCHAR(255) NULL DEFAULT '' COMMENT '短名称 打印需要' ,
CHANGE COLUMN `isdiscount_title` `isdiscount_title` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 促销标题' ,
CHANGE COLUMN `isdiscount_time` `isdiscount_time` INT(11) NULL DEFAULT '0' COMMENT 'v2 促销结束时间' ,
CHANGE COLUMN `isdiscount_discounts` `isdiscount_discounts` TEXT NULL DEFAULT NULL COMMENT 'v2 促销价格 数字为价格 百分数 为折扣' ,
CHANGE COLUMN `commission` `commission` TEXT NULL DEFAULT NULL COMMENT 'v2 分销' ,
CHANGE COLUMN `shopid` `shopid` INT(11) NULL DEFAULT '0' COMMENT 'v2 商户ID' ,
CHANGE COLUMN `allcates` `allcates` TEXT NULL DEFAULT NULL COMMENT 'v2 好象无用' ,
CHANGE COLUMN `minbuy` `minbuy` INT(11) NULL DEFAULT '0' COMMENT 'v2 用户单次必须购买数量' ,
CHANGE COLUMN `invoice` `invoice` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 提供发票' ,
CHANGE COLUMN `repair` `repair` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 保修' ,
CHANGE COLUMN `seven` `seven` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 7天无理由退换' ,
CHANGE COLUMN `money` `money` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 余额返现' ,
CHANGE COLUMN `minprice` `minprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT 'v2 多规格中最小价格，无规格时显示销售价' ,
CHANGE COLUMN `maxprice` `maxprice` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT 'v2 多规格中最大价格，无规格时显示销售价' ,
CHANGE COLUMN `province` `province` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 商品所在省 如为空则显示商城所在' ,
CHANGE COLUMN `city` `city` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 商品所在城市 如为空则显示商城所在' ,
CHANGE COLUMN `buyshow` `buyshow` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 购买后可见 0 关闭 1 开启' ,
CHANGE COLUMN `buycontent` `buycontent` TEXT NULL DEFAULT NULL COMMENT 'v2 购买可见开启后的内容' ,
CHANGE COLUMN `virtualsend` `virtualsend` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 自动发货 0 否 1 是 ，注：自动发货后，订单自动完成' ,
CHANGE COLUMN `virtualsendcontent` `virtualsendcontent` TEXT NULL DEFAULT NULL COMMENT 'v2 自动发货内容' ,
CHANGE COLUMN `verifytype` `verifytype` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 核销类型 0 按订单核销 1 按次核销 2 按消费码核销' ,
CHANGE COLUMN `diyfields` `diyfields` TEXT NULL DEFAULT NULL COMMENT 'v2' ,
CHANGE COLUMN `diysaveid` `diysaveid` INT(11) NULL DEFAULT '0' COMMENT 'v2' ,
CHANGE COLUMN `diysave` `diysave` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2' ,
CHANGE COLUMN `quality` `quality` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 正品保证' ,
CHANGE COLUMN `groupstype` `groupstype` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'v2 是否支持拼团 0 否 1 支持' ,
CHANGE COLUMN `showtotal` `showtotal` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'v2 显示库存 0 不显示 1 显示' ,
CHANGE COLUMN `subtitle` `subtitle` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 子标题' ,
CHANGE COLUMN `sharebtn` `sharebtn` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'v2 分享按钮链接方式 0 弹出关注提示层 1 跳转至商品海报' ,
CHANGE COLUMN `merchid` `merchid` INT(11) NULL DEFAULT '0' COMMENT 'v2 商户ID' ,
CHANGE COLUMN `checked` `checked` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 审核状态' ,
CHANGE COLUMN `thumb_first` `thumb_first` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 详情页面显示首图 0 不显示 1 显示 注：首图为列表页使用，尺寸较小' ,
CHANGE COLUMN `catesinit3` `catesinit3` TEXT NULL DEFAULT NULL COMMENT 'v2 是否初始化分类信息 标识字段无用' ,
CHANGE COLUMN `showtotaladd` `showtotaladd` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 是否调整过显示库存 标识字段无用' ,
CHANGE COLUMN `merchsale` `merchsale` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 手机端使用的价格 0 当前设置促销价格 1 商户设置促销价格' ,
CHANGE COLUMN `keywords` `keywords` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 关键词' ,
CHANGE COLUMN `catch_id` `catch_id` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 抓取产品信息ID' ,
CHANGE COLUMN `catch_url` `catch_url` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 抓取产品地址' ,
CHANGE COLUMN `catch_source` `catch_source` VARCHAR(255) NULL DEFAULT '' COMMENT 'v2 抓取产品来源' ,
CHANGE COLUMN `minpriceupdated` `minpriceupdated` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 是否更新过价格 标识字段无用' ,
CHANGE COLUMN `labelname` `labelname` TEXT NULL DEFAULT NULL COMMENT 'v2 商品标签' ,
CHANGE COLUMN `autoreceive` `autoreceive` INT(11) NULL DEFAULT '0' COMMENT 'v2 自动收货 0 系统设置 -1 不自动收货 >0 天数' ,
CHANGE COLUMN `cannotrefund` `cannotrefund` TINYINT(3) NULL DEFAULT '0' COMMENT 'v2 不允许退货' ,
CHANGE COLUMN `bargain` `bargain` INT(11) NULL DEFAULT '0' COMMENT 'v2 砍价' ,
CHANGE COLUMN `buyagain` `buyagain` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT 'v2 重复购买折扣' ,
CHANGE COLUMN `buyagain_islong` `buyagain_islong` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 购买一次后,以后都使用这个折扣 0 否 1 是' ,
CHANGE COLUMN `buyagain_condition` `buyagain_condition` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 使用条件 0 付款后 1 完成后' ,
CHANGE COLUMN `buyagain_sale` `buyagain_sale` TINYINT(1) NULL DEFAULT '0' COMMENT 'v2 可否使用优惠 （重复购买时,是否与其他优惠共享!其他优惠享受后,再使用这个折扣）' ,
CHANGE COLUMN `buyagain_commission` `buyagain_commission` TEXT NULL DEFAULT NULL COMMENT 'v2 复购分销' ,
CHANGE COLUMN `diypage` `diypage` INT(11) NULL DEFAULT NULL COMMENT 'v2 自定义页面ID' ;

ALTER TABLE `ims_superdesk_shop_goods`
ADD `jd_vop_page_num` VARCHAR(16) NOT NULL DEFAULT '0' COMMENT 'jd_vop_page_num' AFTER `jd_vop_sku`;

------------------------------------------ ims_superdesk_shop_goods ------------------------------------------