CREATE TABLE `ims_superdesk_shop_goods` (
  `id` int(11) NOT NULL COMMENT 'ID',
  `uniacid` int(11) DEFAULT '0',
  `merchid` int(11) DEFAULT '0' COMMENT 'v2 商户ID',
  `pcate` int(11) DEFAULT '0' COMMENT '一级分类ID',
  `ccate` int(11) DEFAULT '0' COMMENT '二级分类ID',
  `tcate` int(11) DEFAULT '0' COMMENT '三级分类ID',
  `cates` text COMMENT '多重分类数据集',
  `pcates` text COMMENT '一级多重分类',
  `ccates` text COMMENT '二级多重分类',
  `tcates` text COMMENT '三级多重分类',
  `type` tinyint(2) DEFAULT '1' COMMENT '类型 1 实体物品 2 虚拟物品 3 虚拟物品(卡密) 4 批发 10 话费流量充值 20 充值卡',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态 0 下架 1 上架 2 赠品上架',
  `displayorder` int(11) DEFAULT '0' COMMENT '显示顺序',
  `title` varchar(100) DEFAULT '' COMMENT '商品名称',
  `thumb` varchar(255) DEFAULT '' COMMENT '商品图',
  `unit` varchar(5) DEFAULT '' COMMENT '商品单位',
  `description` varchar(1000) DEFAULT NULL COMMENT '分享描述',
  `content` text COMMENT '商品详情',
  `goodssn` varchar(50) DEFAULT '' COMMENT '商品编号',
  `productsn` varchar(50) DEFAULT '' COMMENT '商品条码',
  `productprice` decimal(10,2) DEFAULT '0.00' COMMENT '商品原价',
  `marketprice` decimal(10,2) DEFAULT '0.00' COMMENT '商品现价',
  `costprice` decimal(10,2) DEFAULT '0.00' COMMENT '商品成本',
  `originalprice` decimal(10,2) DEFAULT '0.00' COMMENT '原价 好象已经废弃',
  `total` int(10) DEFAULT '0' COMMENT '商品库存',
  `totalcnf` int(11) DEFAULT '0' COMMENT '减库存方式 0 拍下减库存 1 付款减库存 2 永不减库存',
  `sales` int(11) DEFAULT '0' COMMENT '已出售数',
  `salesreal` int(11) DEFAULT '0' COMMENT '实际售出数',
  `spec` varchar(5000) DEFAULT '' COMMENT '商品规格设置',
  `weight` decimal(10,2) DEFAULT '0.00' COMMENT '重量(单位g)',
  `credit` varchar(255) DEFAULT NULL COMMENT '购买赠送积分，如果带%号，则为按成交价比例计算',
  `maxbuy` int(11) DEFAULT '0' COMMENT '单次最多购买量',
  `usermaxbuy` int(11) DEFAULT '0' COMMENT '用户最多购买量',
  `hasoption` int(11) DEFAULT '0' COMMENT '启用商品规则 0 不启用 1 启用',
  `dispatch` int(11) DEFAULT '0' COMMENT '配送',
  `thumb_url` text COMMENT '缩略图地址',
  `isnew` tinyint(1) DEFAULT '0' COMMENT '新上',
  `ishot` tinyint(1) DEFAULT '0' COMMENT '热卖',
  `isdiscount` tinyint(1) DEFAULT '0' COMMENT '促销',
  `isrecommand` tinyint(1) DEFAULT '0' COMMENT '推荐',
  `issendfree` tinyint(1) DEFAULT '0' COMMENT '包邮',
  `istime` tinyint(1) DEFAULT '0' COMMENT '限时卖',
  `iscomment` tinyint(1) DEFAULT '0' COMMENT '允许评价',
  `timestart` int(11) DEFAULT '0' COMMENT '限卖开始时间',
  `timeend` int(11) DEFAULT '0' COMMENT '限卖结束时间',
  `viewcount` int(11) DEFAULT '0' COMMENT '查看次数',
  `hascommission` tinyint(3) DEFAULT '0' COMMENT '是否有分销',
  `commission1_rate` decimal(10,2) DEFAULT '0.00' COMMENT '一级分销比率',
  `commission1_pay` decimal(10,2) DEFAULT '0.00' COMMENT '一级分销固定佣金',
  `commission2_rate` decimal(10,2) DEFAULT '0.00' COMMENT '二级分销比率',
  `commission2_pay` decimal(10,2) DEFAULT '0.00' COMMENT '二级分销固定佣金',
  `commission3_rate` decimal(10,2) DEFAULT '0.00' COMMENT '三级分销比率',
  `commission3_pay` decimal(10,2) DEFAULT '0.00' COMMENT '三级分销固定佣金',
  `score` decimal(10,2) DEFAULT '0.00' COMMENT '得分 好象已经废弃',
  `taobaoid` varchar(255) DEFAULT '' COMMENT '淘宝ID 淘宝助手',
  `taotaoid` varchar(255) DEFAULT '' COMMENT '淘宝ID 淘宝助手',
  `taobaourl` varchar(255) DEFAULT '' COMMENT '淘宝网址 淘宝助手',
  `share_title` varchar(255) DEFAULT '' COMMENT '分享标题',
  `share_icon` varchar(255) DEFAULT '' COMMENT '分享图标',
  `cash` tinyint(3) DEFAULT '0' COMMENT '货到付款 1 不支持 2 支持',
  `commission_thumb` varchar(255) DEFAULT '' COMMENT '海报图片',
  `isnodiscount` tinyint(3) DEFAULT '0' COMMENT '不参与会员折扣',
  `showlevels` text COMMENT '浏览权限',
  `buylevels` text COMMENT '购买权限',
  `showgroups` text COMMENT '会员组浏览权限',
  `buygroups` text COMMENT '会员组购买权限',
  `isverify` tinyint(3) DEFAULT '0' COMMENT '支持线下核销 Null 0 1 不支持 2 支持',
  `storeids` text COMMENT '支持门店ID',
  `noticeopenid` varchar(255) DEFAULT '' COMMENT '商家通知',
  `noticetype` text COMMENT '提醒类型',
  `needfollow` tinyint(3) DEFAULT '0' COMMENT '需要关注',
  `followtip` varchar(255) DEFAULT '' COMMENT '关注事项',
  `followurl` varchar(255) DEFAULT '' COMMENT '关注地址',
  `deduct` decimal(10,2) DEFAULT '0.00',
  `virtual` int(11) DEFAULT '0' COMMENT '虚拟商品模板ID 0 多规格虚拟商品',
  `discounts` text COMMENT '折扣',
  `nocommission` tinyint(3) DEFAULT '0' COMMENT '不执行分销',
  `hidecommission` tinyint(3) DEFAULT '0' COMMENT '隐藏分销按钮',
  `artid` int(11) DEFAULT '0' COMMENT '营销文章ID',
  `detail_logo` varchar(255) DEFAULT '' COMMENT '店铺LOGO',
  `detail_shopname` varchar(255) DEFAULT '' COMMENT '店铺名称',
  `detail_btntext1` varchar(255) DEFAULT '' COMMENT '按钮1名称',
  `detail_btnurl1` varchar(255) DEFAULT '' COMMENT '按钮1链接 默认"查看所有商品"及"默认的全部商品连接"',
  `detail_btntext2` varchar(255) DEFAULT '' COMMENT '按钮2名称',
  `detail_btnurl2` varchar(255) DEFAULT '' COMMENT '按钮2链接 默认"进店逛逛"及"默认的小店或商城连接"',
  `detail_totaltitle` varchar(255) DEFAULT '' COMMENT '全部宝贝x个',
  `deduct2` decimal(10,2) DEFAULT '0.00' COMMENT '余额抵扣 0 支持全额抵扣 -1 不支持余额抵扣 >0 最多抵扣 元',
  `ednum` int(11) DEFAULT '0' COMMENT '单品满件包邮 0 : 不支持满件包邮',
  `edmoney` decimal(10,2) DEFAULT '0.00' COMMENT '单品满额包邮 0 : 不支持满额包邮',
  `edareas` text COMMENT '不参加满包邮的地区 ，0 : 不支持满件包邮',
  `diyformtype` tinyint(1) DEFAULT '0' COMMENT '自定义表单类型 0 关闭 1 附加形式 2 替换模式',
  `diyformid` int(11) DEFAULT '0' COMMENT '自定义表单ID',
  `diymode` tinyint(1) DEFAULT '0' COMMENT '自定义表单模式 0 系统默认 1 点击立即购买时填写 2 确认订单时填写',
  `dispatchtype` tinyint(1) DEFAULT '0' COMMENT '配送类型 0 运费模板 1 统一邮费',
  `dispatchid` int(11) DEFAULT '0' COMMENT '配送ID',
  `dispatchprice` decimal(10,2) DEFAULT '0.00' COMMENT '统一邮费',
  `manydeduct` tinyint(1) DEFAULT '0' COMMENT '多件累计抵扣积分',
  `shorttitle` varchar(255) DEFAULT '' COMMENT '短名称 打印需要',
  `isdiscount_title` varchar(255) DEFAULT '' COMMENT 'v2 促销标题',
  `isdiscount_time` int(11) DEFAULT '0' COMMENT 'v2 促销结束时间',
  `isdiscount_discounts` text COMMENT 'v2 促销价格 数字为价格 百分数 为折扣',
  `commission` text COMMENT 'v2 分销',
  `shopid` int(11) DEFAULT '0' COMMENT 'v2 商户ID',
  `allcates` text COMMENT 'v2 好象无用',
  `minbuy` int(11) DEFAULT '0' COMMENT 'v2 用户单次必须购买数量',
  `invoice` tinyint(3) DEFAULT '0' COMMENT 'v2 提供发票',
  `repair` tinyint(3) DEFAULT '0' COMMENT 'v2 保修',
  `seven` tinyint(3) DEFAULT '0' COMMENT 'v2 7天无理由退换',
  `money` varchar(255) DEFAULT '' COMMENT 'v2 余额返现',
  `minprice` decimal(10,2) DEFAULT '0.00' COMMENT 'v2 多规格中最小价格，无规格时显示销售价',
  `maxprice` decimal(10,2) DEFAULT '0.00' COMMENT 'v2 多规格中最大价格，无规格时显示销售价',
  `province` varchar(255) DEFAULT '' COMMENT 'v2 商品所在省 如为空则显示商城所在',
  `city` varchar(255) DEFAULT '' COMMENT 'v2 商品所在城市 如为空则显示商城所在',
  `buyshow` tinyint(1) DEFAULT '0' COMMENT 'v2 购买后可见 0 关闭 1 开启',
  `buycontent` text COMMENT 'v2 购买可见开启后的内容',
  `virtualsend` tinyint(1) DEFAULT '0' COMMENT 'v2 自动发货 0 否 1 是 ，注：自动发货后，订单自动完成',
  `virtualsendcontent` text COMMENT 'v2 自动发货内容',
  `verifytype` tinyint(1) DEFAULT '0' COMMENT 'v2 核销类型 0 按订单核销 1 按次核销 2 按消费码核销',
  `diyfields` text COMMENT 'v2',
  `diysaveid` int(11) DEFAULT '0' COMMENT 'v2',
  `diysave` tinyint(1) DEFAULT '0' COMMENT 'v2',
  `quality` tinyint(3) DEFAULT '0' COMMENT 'v2 正品保证',
  `groupstype` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'v2 是否支持拼团 0 否 1 支持',
  `showtotal` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'v2 显示库存 0 不显示 1 显示',
  `subtitle` varchar(255) DEFAULT '' COMMENT 'v2 子标题',
  `sharebtn` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'v2 分享按钮链接方式 0 弹出关注提示层 1 跳转至商品海报',
  `checked` tinyint(3) DEFAULT '0' COMMENT 'v2 审核状态',
  `thumb_first` tinyint(3) DEFAULT '0' COMMENT 'v2 详情页面显示首图 0 不显示 1 显示 注：首图为列表页使用，尺寸较小',
  `catesinit3` text COMMENT 'v2 是否初始化分类信息 标识字段无用',
  `showtotaladd` tinyint(1) DEFAULT '0' COMMENT 'v2 是否调整过显示库存 标识字段无用',
  `merchsale` tinyint(1) DEFAULT '0' COMMENT 'v2 手机端使用的价格 0 当前设置促销价格 1 商户设置促销价格',
  `keywords` varchar(255) DEFAULT '' COMMENT 'v2 关键词',
  `catch_id` varchar(255) DEFAULT '' COMMENT 'v2 抓取产品信息ID',
  `catch_url` varchar(255) DEFAULT '' COMMENT 'v2 抓取产品地址',
  `catch_source` varchar(255) DEFAULT '' COMMENT 'v2 抓取产品来源',
  `minpriceupdated` tinyint(1) DEFAULT '0' COMMENT 'v2 是否更新过价格 标识字段无用',
  `labelname` text COMMENT 'v2 商品标签',
  `autoreceive` int(11) DEFAULT '0' COMMENT 'v2 自动收货 0 系统设置 -1 不自动收货 >0 天数',
  `cannotrefund` tinyint(3) DEFAULT '0' COMMENT 'v2 不允许退货',
  `bargain` int(11) DEFAULT '0' COMMENT 'v2 砍价',
  `buyagain` decimal(10,2) DEFAULT '0.00' COMMENT 'v2 重复购买折扣',
  `diypage` int(11) DEFAULT NULL COMMENT 'v2 自定义页面ID',
  `buyagain_islong` tinyint(1) DEFAULT '0' COMMENT 'v2 购买一次后,以后都使用这个折扣 0 否 1 是',
  `buyagain_condition` tinyint(1) DEFAULT '0' COMMENT 'v2 使用条件 0 付款后 1 完成后',
  `buyagain_sale` tinyint(1) DEFAULT '0' COMMENT 'v2 可否使用优惠 （重复购买时,是否与其他优惠共享!其他优惠享受后,再使用这个折扣）',
  `buyagain_commission` text COMMENT 'v2 复购分销',
  `jd_vop_sku` int(11) NOT NULL DEFAULT '0',
  `jd_vop_page_num` varchar(16) NOT NULL DEFAULT '0' COMMENT 'jd_vop_page_num',
  `old_shop_goods_id` int(11) NOT NULL DEFAULT '0' COMMENT 'old_shop_goods_id',
  `createtime` int(11) DEFAULT '0' COMMENT '建立时间',
  `updatetime` int(11) DEFAULT '0' COMMENT '更新时间',
  `deleted` tinyint(3) DEFAULT '0' COMMENT '是否删除',
  `synctime_jd_vop_price` int(11) NOT NULL DEFAULT '0' COMMENT 'synctime_jd_vop_price'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `ims_superdesk_shop_goods`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_uniacid` (`uniacid`) USING BTREE,
  ADD KEY `idx_pcate` (`pcate`) USING BTREE,
  ADD KEY `idx_ccate` (`ccate`) USING BTREE,
  ADD KEY `idx_isnew` (`isnew`) USING BTREE,
  ADD KEY `idx_ishot` (`ishot`) USING BTREE,
  ADD KEY `idx_isdiscount` (`isdiscount`) USING BTREE,
  ADD KEY `idx_isrecommand` (`isrecommand`) USING BTREE,
  ADD KEY `idx_iscomment` (`iscomment`) USING BTREE,
  ADD KEY `idx_issendfree` (`issendfree`) USING BTREE,
  ADD KEY `idx_istime` (`istime`) USING BTREE,
  ADD KEY `idx_deleted` (`deleted`) USING BTREE,
  ADD KEY `idx_tcate` (`tcate`) USING BTREE,
  ADD KEY `idx_merchid` (`merchid`) USING BTREE,
  ADD KEY `idx_checked` (`checked`) USING BTREE,
  ADD KEY `jd_vop_sku` (`jd_vop_sku`) USING BTREE,
  ADD KEY `idx_status` (`status`) USING BTREE,
  ADD KEY `idx_union1` (`uniacid`,`status`,`deleted`,`checked`,`displayorder`,`createtime`) USING BTREE,
  ADD KEY `idx_union2` (`uniacid`,`status`,`deleted`,`minprice`,`checked`,`displayorder`,`createtime`) USING BTREE,
  ADD KEY `idx_union_4_sku_dto_2_redis_queue` (`uniacid`,`status`,`deleted`,`jd_vop_sku`,`updatetime`);
ALTER TABLE `ims_superdesk_shop_goods` ADD FULLTEXT KEY `idx_buylevels` (`buylevels`);
ALTER TABLE `ims_superdesk_shop_goods` ADD FULLTEXT KEY `idx_showgroups` (`showgroups`);
ALTER TABLE `ims_superdesk_shop_goods` ADD FULLTEXT KEY `idx_buygroups` (`buygroups`);

ALTER TABLE `ims_superdesk_shop_goods` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID';