SELECT
    id,uniacid,pcate,ccate,tcate,`type`,
    status*1 as status,
    displayorder,title,
    thumb,unit,description,content,goodssn,productsn,productprice,marketprice,costprice,originalprice,
    total,totalcnf,sales,salesreal,spec,createtime,weight,credit,maxbuy,usermaxbuy,hasoption,dispatch,thumb_url,
    isnew*1 as isnew,
    ishot*1 as ishot,
    isdiscount*1 as isdiscount,
    isrecommand*1 as isrecommand,
    issendfree*1 as issendfree,
    istime*1 as istime,
    iscomment*1 as iscomment,
    timestart,timeend,viewcount,
    deleted,
    hascommission,
    commission1_rate,
    commission1_pay,
    commission2_rate,
    commission2_pay,
    commission3_rate,
    commission3_pay,
    score,taobaoid,taotaoid,taobaourl,updatetime,share_title,share_icon,cash,commission_thumb,isnodiscount,
    showlevels,buylevels,showgroups,buygroups,isverify,storeids,noticeopenid,noticetype,needfollow,followtip,followurl,
    deduct,
    `virtual`,ccates,discounts,
    nocommission,
    hidecommission,
    pcates,cates,tcates,
    artid,
    detail_logo,detail_shopname,detail_btntext1,detail_btnurl1,detail_btntext2,detail_btnurl2,detail_totaltitle,
    deduct2,ednum,edmoney,edareas,
    diyformtype*1 as diyformtype,
    diyformid,
    diymode*1 as diymode,
    dispatchtype*1 as dispatchtype,
    dispatchid,dispatchprice,
    manydeduct*1 as manydeduct,
    shorttitle,
    isdiscount_title,
    isdiscount_time,
    isdiscount_discounts,commission,shopid,allcates,minbuy,minprice,
    invoice,repair,seven,money,maxprice,province,city,
    buyshow*1 as buyshow,
    buycontent,
    virtualsend*1 as virtualsend,
    virtualsendcontent,
    verifytype*1 as verifytype,
    diyfields,diysaveid,
    diysave*1 as diysave,
    quality,
    groupstype*1 as groupstype,
    showtotal*1 as showtotal,
    subtitle,
    sharebtn*1 as sharebtn,
    merchid,checked,thumb_first,catesinit3,
    showtotaladd*1 as showtotaladd,
    merchsale*1 as merchsale,
    keywords,catch_id,catch_url,catch_source,
    minpriceupdated*1 as minpriceupdated,
    labelname,autoreceive,cannotrefund,
    bargain,
    buyagain,
    buyagain_islong*1 as buyagain_islong,
    buyagain_condition*1 as buyagain_condition,
    buyagain_sale*1 as buyagain_sale,
    buyagain_commission,
    diypage,
    jd_vop_sku,jd_vop_page_num
FROM
  ims_superdesk_shop_goods
where
  updatetime >= :sql_last_value
ORDER BY updatetime ASC
